version: "3"

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    container_name: "database"
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: learning
    ports:
      - "3306:3306"
    restart: always
