spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/learning?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=CET
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml



token:
  jwtSecret: secretKey
  jwtExpirationInMs: 86400000
#swagger ui
#http://localhost:8080/swagger-ui.html